[book]
title = "Note Book"
description = "My personal knowledge base"
authors = ["Aniket Kakde"]
language = "en"
src = "src"

[rust]
edition = "2021"

[output.html]
default-theme = "snow-storm"
preferred-dark-theme = "polar-night"
smart-punctuation = true
mathjax-support = true
git-repository-url = "https://github.com/ani2fun/note-book/tree/main"
additional-css = ["theme/custom.css", "theme/extra-themes.css", "theme/pagetoc.css"]
additional-js = [
  "theme/mermaid-init.js",
  "theme/extra-themes.js",
  "theme/lang-tabs.js",
  "theme/python-playground.js",
  "theme/sql-playground.js",
  "theme/ts-playground.js",
  "theme/piston-playground.js",
  "theme/pagetoc.js",
  "theme/pagetoc-mobile.js",
  "theme/d2-slides.js",
  "theme/array-stepper.js"
]

[preprocessor.d2]
command = "mdbook-d2"
renderer = ["html"]

[preprocessor.pagetoc]
scroll_offset = 10

[output.html.playground]
editable = true
copyable = true
line-numbers = true

[output.html.code.hidelines]
python = "~"

[output.html.fold]
enable = true
level = 1

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2
