services:
  mdbook:
    build:
      context: .
      dockerfile: Dockerfile
      target: mdbook-tools
    working_dir: /app
    ports:
      - "3000:3000"  # Expose the mdbook server on localhost:3000
    volumes:
      - .:/app  # Mount the current directory to /app inside the container for live updates
    command: ["sh", "-lc", "mdbook-admonish install . || true && mdbook serve -n 0.0.0.0"]  # Serve the book with mdbook
